# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.0
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean package
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.1
      with:
        name: JDK 11 Build
        path: ${{ github.workspace }}/target
    - name: list
      run: |
        ls
        cd target
        ls
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/target/Usage_Checker-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        tag: continuous # ${{ github.ref }}
        overwrite: true
